services:
  op-connect-api:
    image: 1password/connect-api:latest
    container_name: 1password-connect-api
    restart: unless-stopped
    ports:
      - "8380:8080"
    volumes:
      - /mnt/main/appdata/1password/1password-credentials.json:/home/opuser/.op/1password-credentials.json
      - 1password-data:/home/opuser/.op/data

  op-connect-sync:
    image: 1password/connect-sync:latest
    container_name: 1password-connect-sync
    restart: unless-stopped
    ports:
      - "8381:8080"
    volumes:
      - /mnt/main/appdata/1password/1password-credentials.json:/home/opuser/.op/1password-credentials.json
      - 1password-data:/home/opuser/.op/data

volumes:
  1password-data:
