app:
  dashboard_url: "op://Dev/Pangolin/Server/DASHBOARD_URL"
  anonymous_usage: false

domains:
  chasepie_com:
    base_domain: "chasepie.com"
    cert_resolver: "letsencrypt"
    prefer_wildcard_cert: true

server:
  secret: "op://Dev/Pangolin/Server/SERVER_SECRET"

gerbil:
  base_endpoint: "op://Dev/Pangolin/Server/BASE_ENDPOINT"

flags:
  require_email_verification: false
  disable_signup_without_invite: true
  disable_user_create_org: true
