services:
  app:
    image: ghcr.io/chasepie/site-checker:latest
    container_name: site-checker
    restart: unless-stopped
    networks:
      - default
      - pangolin
    ports:
      - 8080:8080
    env_file: .env
    environment:
      - TZ=America/Detroit
      - BROWSERLESS_URL=ws://browserless:3000
      - BROWSERLESS_URL_VPN=ws://vpn:3000
    volumes:
      - /mnt/main/appdata/site-checker/data:/app/Database/data
      - /mnt/main/appdata/site-checker/logs:/app/Logs
      - /mnt/main/appdata/site-checker/pia:/pia
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - browserless
      - browserless-vpn

  browserless:
    image: ghcr.io/browserless/chromium:latest
    container_name: site-checker-browserless
    restart: unless-stopped
    env_file: .env
    environment:
      - TZ=America/Detroit
      - TOKEN=${BROWSERLESS_TOKEN}
      - TIMEOUT=180000

  browserless-vpn:
    image: ghcr.io/browserless/chromium:latest
    container_name: site-checker-browserless-vpn
    restart: unless-stopped
    env_file: .env
    environment:
      - TZ=America/Detroit
      - TOKEN=${BROWSERLESS_TOKEN}
      - TIMEOUT=180000
    network_mode: "service:vpn"
    depends_on:
      vpn:
        condition: service_healthy

  vpn:
    image: thrnz/docker-wireguard-pia:latest
    container_name: site-checker-vpn
    restart: unless-stopped
    volumes:
      - /mnt/main/appdata/site-checker/pia:/pia
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    env_file: .env
    environment:
      - TZ=America/Detroit
      - USER=${PIA_USERNAME}
      - PASS=${PIA_PASSWORD}
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    command: >
      /bin/bash -c "[ -f /pia/loc.txt ] || echo 'us_michigan-pf' > /pia/loc.txt
      && LOC=$(cat /pia/loc.txt) /scripts/run"

networks:
  pangolin:
    external: true
