---
services:
  # https://github.com/linuxserver/docker-firefox?tab=readme-ov-file#docker-compose-recommended-click-here-for-more-info
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - FIREFOX_CLI=https://www.linuxserver.io/ #optional

      # https://github.com/linuxserver/docker-firefox?tab=readme-ov-file#hardware-acceleration--the-move-to-wayland
      # - PIXELFLUX_WAYLAND=true
      # Ensure these point to the rendered node injected by the runtime (usually renderD128)
      # - DRINODE=/dev/dri/renderD128
      # - DRI_NODE=/dev/dri/renderD128
    volumes:
      - /mnt/main/appdata/firefox/config:/config
    shm_size: "1gb"
    network_mode: "service:vpn"
    depends_on:
      vpn:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [compute, video, graphics, utility]

  vpn:
    image: thrnz/docker-wireguard-pia
    container_name: firefox-pia
    volumes:
      - firefox-pia:/pia
      - firefox-pia-shared:/pia-shared
    cap_add:
      - NET_ADMIN
    # If the kernel module isn't available, mounting the tun device may be necessary for userspace implementations
    #devices:
    #- /dev/net/tun:/dev/net/tun
    ports:
      - 3200:3000
      - 3201:3001
    env_file:
      - .env
    environment:
      - LOC=${LOC:-us_michigan-pf}
      - USER=${PIA_USERNAME}
      - PASS=${PIA_PASSWORD}
      - ACTIVE_HEALTHCHECKS=1
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1

volumes:
  firefox-pia:
  firefox-pia-shared:
