- name: Update Linux servers
  hosts: all
  become: true
  tasks:
    - name: Configure automatic package upgrades
      ansible.builtin.include_tasks: ../tasks/configure-auto-upgrades.debian.yml

    - name: Update packages
      ansible.builtin.include_tasks: ../tasks/update-packages.debian.yml

    - name: Update Komodo services
      ansible.builtin.include_tasks: ../tasks/update-docker-compose.yml
      loop:
        - /srv/docker/komodo
        - /srv/docker/komodo-periphery
      loop_control:
        loop_var: compose_dir
