- name: Update apt cache and upgrade packages (Debian/Ubuntu)
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
    autoremove: true
    autoclean: true
  when: ansible_facts['os_family'] == "Debian"

- name: Check if reboot is required (Debian/Ubuntu)
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_debian
  when: ansible_facts['os_family'] == "Debian"

- name: Reboot if required (Debian/Ubuntu)
  ansible.builtin.reboot:
    msg: "Reboot triggered by Ansible update playbook"
  when:
    - ansible_facts['os_family'] == "Debian"
    - reboot_required_debian.stat.exists
