#
# WARNING: To install Immich, follow our guide: https://docs.immich.app/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-microservices:
    container_name: immich-microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: nvenc # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      IMMICH_WORKERS_INCLUDE: "microservices"
      REDIS_HOSTNAME: "192.168.70.102"
      REDIS_PORT: "2284"
      DB_HOSTNAME: "192.168.70.102"
      DB_PORT: "2285"
      DB_DATA_LOCATION: # unset
      UPLOAD_LOCATION: # unset
    restart: unless-stopped
    healthcheck:
      disable: false
