services:
  newt:
    image: fosrl/newt
    container_name: newt
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file: .env
    environment:
      - PANGOLIN_ENDPOINT=https://pangolin.chasepie.com
      - DOCKER_SOCKET=unix:///var/run/docker.sock

networks:
  default:
    driver: bridge
    name: pangolin
